### ISSUE TITLE
双击笔记内文导致标签页关闭

### ISSUE THREAD

**Issue by Dirtyuri** [Quorafind/Obsidian-Double-Click-Tab#6]
![1665925533812](https://user-images.githubusercontent.com/68465099/196037206-c59d257e-1411-48db-a4dc-c28616c5c0de.gif)

插件版本1.1.0，此外还安装了1.8.2版中文分词插件

**Comment by Dirtyuri** [comment]
> ![1665925533812](https://user-images.githubusercontent.com/68465099/196037206-c59d257e-1411-48db-a4dc-c28616c5c0de.gif) [ ![1665925533812](https://user-images.githubusercontent.com/68465099/196037206-c59d257e-1411-48db-a4dc-c28616c5c0de.gif) ](https://user-images.githubusercontent.com/68465099/196037206-c59d257e-1411-48db-a4dc-c28616c5c0de.gif) [ ](https://user-images.githubusercontent.com/68465099/196037206-c59d257e-1411-48db-a4dc-c28616c5c0de.gif)

**Comment by Quorafind** [comment]
更新 1.1.1
